import type { Equipment, GoalType, PatternTag, QuestBlock, QuestKind } from "@arise/domain";
import { BASE_XP } from "../xp.js";

export const EXPANSION_IDS = [
  "yoga_cat_cow",
  "yoga_child",
  "yoga_down_dog",
  "yoga_mountain",
  "yoga_warrior2",
  "yoga_bridge",
  "yoga_supine_twist",
  "yoga_legs_wall",
  "yoga_seated_fold",
  "yoga_sphinx",
  "yoga_thread_needle",
  "gym_bench_press",
  "gym_incline_db_press",
  "gym_chest_supported",
  "gym_lat_pulldown",
  "gym_seated_row",
  "gym_chest_row",
  "gym_ohp",
  "gym_lateral_raise",
  "gym_back_squat",
  "gym_leg_press",
  "gym_lunge",
  "gym_rdl",
  "gym_hip_thrust",
  "gym_curl",
  "gym_tricep_pushdown",
  "gym_dead_bug",
  "gym_side_plank",
] as const;

export type ExpansionId = (typeof EXPANSION_IDS)[number];

export interface ExpansionSpec {
  id: ExpansionId;
  kind: QuestKind;
  title: string;
  flavor: string;
  goalTags: GoalType[];
  patternTags: PatternTag[];
  requiredAny: Equipment[];
  contraindicationKeys: string[];
  minExperience: 0 | 1 | 2 | 3;
  baseMinutes: number;
  intensity: "rest" | "easy" | "moderate" | "hard";
  statDelta: Partial<Record<"str" | "agi" | "vit" | "intl" | "sta", number>>;
  baseXp: number;
  autoCompletable: boolean;
  blocks: QuestBlock[];
  ignoreBudget?: boolean;
}

const YOGA_GOALS: GoalType[] = ["mobility", "general_fitness"];
const GYM_GOALS: GoalType[] = ["muscle_gain", "recomposition", "general_fitness"];

export const GYM_PRIMARY_BY_FOCUS: Record<string, readonly ExpansionId[]> = {
  push: ["gym_bench_press", "gym_incline_db_press", "gym_chest_supported", "gym_ohp"],
  pull: ["gym_lat_pulldown", "gym_seated_row", "gym_chest_row"],
  legs: ["gym_back_squat", "gym_leg_press", "gym_lunge", "gym_rdl", "gym_hip_thrust"],
  full_body: [
    "gym_bench_press",
    "gym_lat_pulldown",
    "gym_back_squat",
    "gym_rdl",
    "gym_ohp",
    "gym_seated_row",
  ],
  mixed: ["gym_bench_press", "gym_seated_row", "gym_rdl", "gym_lunge"],
};

export const GYM_ACCESSORY_IDS: readonly ExpansionId[] = [
  "gym_lateral_raise",
  "gym_curl",
  "gym_tricep_pushdown",
  "gym_dead_bug",
  "gym_side_plank",
];

export const EXPANSION_SPECS: ExpansionSpec[] = [
  {
    id: "yoga_cat_cow",
    kind: "yoga",
    title: "Cat–Cow",
    flavor: "Slow spinal waves on hands and knees.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga", "mobility_tspine"],
    requiredAny: ["none"],
    contraindicationKeys: ["spine"],
    minExperience: 0,
    baseMinutes: 5,
    intensity: "easy",
    statDelta: { vit: 0.22, intl: 0.08 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Cat–cow", sets: 2, reps: 8, rpeMax: 2 }],
  },
  {
    id: "yoga_child",
    kind: "yoga",
    title: "Child’s Pose",
    flavor: "Hips toward the heels. Quiet breath.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga", "breath"],
    requiredAny: ["none"],
    contraindicationKeys: ["knee"],
    minExperience: 0,
    baseMinutes: 4,
    intensity: "rest",
    statDelta: { vit: 0.16, intl: 0.1 },
    baseXp: BASE_XP.recovery,
    autoCompletable: false,
    blocks: [{ name: "Child’s pose", sets: 2, seconds: 45, rpeMax: 1 }],
  },
  {
    id: "yoga_down_dog",
    kind: "yoga",
    title: "Downward Dog",
    flavor: "Hips high, soft knees, long spine.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga"],
    requiredAny: ["none"],
    contraindicationKeys: ["wrist", "shoulder"],
    minExperience: 0,
    baseMinutes: 5,
    intensity: "easy",
    statDelta: { vit: 0.2, sta: 0.08 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Downward dog", sets: 3, seconds: 25, rpeMax: 3 }],
  },
  {
    id: "yoga_mountain",
    kind: "yoga",
    title: "Mountain",
    flavor: "Stand tall. Quiet breath.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga", "breath"],
    requiredAny: ["none"],
    contraindicationKeys: [],
    minExperience: 0,
    baseMinutes: 3,
    intensity: "rest",
    statDelta: { intl: 0.14, vit: 0.08 },
    baseXp: BASE_XP.recovery,
    autoCompletable: false,
    blocks: [{ name: "Mountain", seconds: 75, rpeMax: 1 }],
  },
  {
    id: "yoga_warrior2",
    kind: "yoga",
    title: "Warrior II",
    flavor: "Front knee tracks the toes. Back leg long.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga"],
    requiredAny: ["none"],
    contraindicationKeys: ["knee"],
    minExperience: 0,
    baseMinutes: 6,
    intensity: "easy",
    statDelta: { sta: 0.12, vit: 0.16 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Warrior II", sets: 2, seconds: 30, rpeMax: 3, notes: "per side" }],
  },
  {
    id: "yoga_bridge",
    kind: "yoga",
    title: "Glute Bridge",
    flavor: "Lift the hips. Soft neck.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga", "hinge"],
    requiredAny: ["none"],
    contraindicationKeys: ["spine"],
    minExperience: 0,
    baseMinutes: 6,
    intensity: "easy",
    statDelta: { str: 0.12, vit: 0.16 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Glute bridge", sets: 2, reps: 8, rpeMax: 3, notes: "2 s squeeze" }],
  },
  {
    id: "yoga_supine_twist",
    kind: "yoga",
    title: "Supine Twist",
    flavor: "Knees to one side. Opposite shoulder heavy.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga", "mobility_tspine"],
    requiredAny: ["none"],
    contraindicationKeys: ["spine"],
    minExperience: 0,
    baseMinutes: 5,
    intensity: "easy",
    statDelta: { vit: 0.2, intl: 0.08 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Supine twist", sets: 2, seconds: 30, rpeMax: 2, notes: "per side" }],
  },
  {
    id: "yoga_legs_wall",
    kind: "yoga",
    title: "Legs Up Wall",
    flavor: "Legs vertical. Easy arms.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga", "breath"],
    requiredAny: ["none"],
    contraindicationKeys: [],
    minExperience: 0,
    baseMinutes: 6,
    intensity: "rest",
    statDelta: { vit: 0.14, intl: 0.12 },
    baseXp: BASE_XP.recovery,
    autoCompletable: false,
    blocks: [{ name: "Legs up the wall", seconds: 240, rpeMax: 1 }],
  },
  {
    id: "yoga_seated_fold",
    kind: "yoga",
    title: "Seated Fold",
    flavor: "Hinge from the hips. Long spine.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga"],
    requiredAny: ["none"],
    contraindicationKeys: ["spine"],
    minExperience: 0,
    baseMinutes: 5,
    intensity: "easy",
    statDelta: { vit: 0.18 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Seated fold", sets: 2, seconds: 30, rpeMax: 2 }],
  },
  {
    id: "yoga_sphinx",
    kind: "yoga",
    title: "Sphinx",
    flavor: "Gentle chest lift. Pubic bone heavy.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga"],
    requiredAny: ["none"],
    contraindicationKeys: ["spine"],
    minExperience: 0,
    baseMinutes: 4,
    intensity: "easy",
    statDelta: { vit: 0.16 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Sphinx", sets: 2, seconds: 25, rpeMax: 2 }],
  },
  {
    id: "yoga_thread_needle",
    kind: "yoga",
    title: "Thread the Needle",
    flavor: "Slide one arm under. Rest the shoulder.",
    goalTags: YOGA_GOALS,
    patternTags: ["yoga", "mobility_tspine"],
    requiredAny: ["none"],
    contraindicationKeys: ["shoulder"],
    minExperience: 0,
    baseMinutes: 5,
    intensity: "easy",
    statDelta: { vit: 0.18 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Thread the needle", sets: 2, reps: 4, rpeMax: 2, notes: "per side" }],
  },
  {
    id: "gym_bench_press",
    kind: "strength",
    title: "Bench Press",
    flavor: "Bar to mid-chest. Wrists stacked.",
    goalTags: GYM_GOALS,
    patternTags: ["push"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["shoulder", "wrist"],
    minExperience: 2,
    baseMinutes: 18,
    intensity: "hard",
    statDelta: { str: 0.38, sta: 0.08 },
    baseXp: BASE_XP.gate,
    autoCompletable: false,
    blocks: [{ name: "Bench press", sets: 3, reps: 5, rpeMax: 7, restSec: 90 }],
  },
  {
    id: "gym_incline_db_press",
    kind: "strength",
    title: "Incline DB Press",
    flavor: "30–45° bench. DBs over the chest.",
    goalTags: GYM_GOALS,
    patternTags: ["push"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["shoulder"],
    minExperience: 2,
    baseMinutes: 16,
    intensity: "moderate",
    statDelta: { str: 0.34 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Incline DB press", sets: 3, reps: 8, rpeMax: 7, restSec: 75 }],
  },
  {
    id: "gym_chest_supported",
    kind: "strength",
    title: "Machine Chest Press",
    flavor: "Supported press. Control the return.",
    goalTags: GYM_GOALS,
    patternTags: ["push"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["shoulder"],
    minExperience: 2,
    baseMinutes: 14,
    intensity: "moderate",
    statDelta: { str: 0.3 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Machine chest press", sets: 3, reps: 8, rpeMax: 7, restSec: 75 }],
  },
  {
    id: "gym_lat_pulldown",
    kind: "strength",
    title: "Lat Pulldown",
    flavor: "Bar to the upper chest. Not behind the neck.",
    goalTags: GYM_GOALS,
    patternTags: ["pull"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["shoulder"],
    minExperience: 2,
    baseMinutes: 14,
    intensity: "moderate",
    statDelta: { str: 0.32, vit: 0.08 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Lat pulldown", sets: 3, reps: 8, rpeMax: 7, restSec: 75 }],
  },
  {
    id: "gym_seated_row",
    kind: "strength",
    title: "Seated Cable Row",
    flavor: "Long spine. Pull to the low ribs.",
    goalTags: GYM_GOALS,
    patternTags: ["pull"],
    requiredAny: ["full_gym"],
    contraindicationKeys: [],
    minExperience: 2,
    baseMinutes: 14,
    intensity: "moderate",
    statDelta: { str: 0.3, vit: 0.1 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Seated cable row", sets: 3, reps: 10, rpeMax: 7, restSec: 75 }],
  },
  {
    id: "gym_chest_row",
    kind: "strength",
    title: "Chest-supported Row",
    flavor: "Supported chest. Pull to the ribs.",
    goalTags: GYM_GOALS,
    patternTags: ["pull"],
    requiredAny: ["full_gym"],
    contraindicationKeys: [],
    minExperience: 2,
    baseMinutes: 14,
    intensity: "moderate",
    statDelta: { str: 0.3, vit: 0.08 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Chest-supported row", sets: 3, reps: 8, rpeMax: 7, restSec: 75 }],
  },
  {
    id: "gym_ohp",
    kind: "strength",
    title: "Overhead Press",
    flavor: "Brace. Press up. Ribs stacked.",
    goalTags: GYM_GOALS,
    patternTags: ["push"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["shoulder"],
    minExperience: 2,
    baseMinutes: 16,
    intensity: "hard",
    statDelta: { str: 0.36, sta: 0.08 },
    baseXp: BASE_XP.gate,
    autoCompletable: false,
    blocks: [{ name: "Overhead press", sets: 3, reps: 5, rpeMax: 7, restSec: 90 }],
  },
  {
    id: "gym_lateral_raise",
    kind: "strength",
    title: "Lateral Raise",
    flavor: "Soft elbows. Raise to shoulder height.",
    goalTags: GYM_GOALS,
    patternTags: ["push"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["shoulder"],
    minExperience: 2,
    baseMinutes: 8,
    intensity: "easy",
    statDelta: { str: 0.16 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Lateral raise", sets: 2, reps: 10, rpeMax: 6, restSec: 45 }],
  },
  {
    id: "gym_back_squat",
    kind: "strength",
    title: "Back Squat",
    flavor: "Bar on the upper back. Knees track toes.",
    goalTags: GYM_GOALS,
    patternTags: ["squat"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["knee", "spine"],
    minExperience: 2,
    baseMinutes: 20,
    intensity: "hard",
    statDelta: { str: 0.4, sta: 0.1 },
    baseXp: BASE_XP.gate,
    autoCompletable: false,
    blocks: [{ name: "Back squat", sets: 3, reps: 5, rpeMax: 7, restSec: 120 }],
  },
  {
    id: "gym_leg_press",
    kind: "strength",
    title: "Leg Press",
    flavor: "Low back on the pad. No hard lockout.",
    goalTags: GYM_GOALS,
    patternTags: ["squat"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["knee"],
    minExperience: 2,
    baseMinutes: 16,
    intensity: "moderate",
    statDelta: { str: 0.32, sta: 0.1 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Leg press", sets: 3, reps: 8, rpeMax: 7, restSec: 90 }],
  },
  {
    id: "gym_lunge",
    kind: "strength",
    title: "Walking Lunge",
    flavor: "Front knee tracks the mid-foot.",
    goalTags: GYM_GOALS,
    patternTags: ["squat"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["knee"],
    minExperience: 2,
    baseMinutes: 14,
    intensity: "moderate",
    statDelta: { str: 0.28, agi: 0.1 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Walking lunge", sets: 2, reps: 8, rpeMax: 6, restSec: 75, notes: "per side" }],
  },
  {
    id: "gym_rdl",
    kind: "strength",
    title: "Romanian Deadlift",
    flavor: "Hips back. Bar close. Long spine.",
    goalTags: GYM_GOALS,
    patternTags: ["hinge"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["spine"],
    minExperience: 2,
    baseMinutes: 16,
    intensity: "hard",
    statDelta: { str: 0.36, vit: 0.1 },
    baseXp: BASE_XP.gate,
    autoCompletable: false,
    blocks: [{ name: "Romanian deadlift", sets: 3, reps: 5, rpeMax: 7, restSec: 90 }],
  },
  {
    id: "gym_hip_thrust",
    kind: "strength",
    title: "Hip Thrust",
    flavor: "Upper back on a bench. Chin tucked.",
    goalTags: GYM_GOALS,
    patternTags: ["hinge"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["spine"],
    minExperience: 2,
    baseMinutes: 14,
    intensity: "moderate",
    statDelta: { str: 0.3, vit: 0.08 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Hip thrust", sets: 3, reps: 8, rpeMax: 7, restSec: 75 }],
  },
  {
    id: "gym_curl",
    kind: "strength",
    title: "DB Curl",
    flavor: "Elbows quiet. No swing.",
    goalTags: GYM_GOALS,
    patternTags: ["pull"],
    requiredAny: ["full_gym"],
    contraindicationKeys: [],
    minExperience: 2,
    baseMinutes: 8,
    intensity: "easy",
    statDelta: { str: 0.14 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "DB curl", sets: 2, reps: 10, rpeMax: 6, restSec: 45 }],
  },
  {
    id: "gym_tricep_pushdown",
    kind: "strength",
    title: "Tricep Pushdown",
    flavor: "Elbows by the ribs.",
    goalTags: GYM_GOALS,
    patternTags: ["push"],
    requiredAny: ["full_gym"],
    contraindicationKeys: ["shoulder", "wrist"],
    minExperience: 2,
    baseMinutes: 8,
    intensity: "easy",
    statDelta: { str: 0.14 },
    baseXp: BASE_XP.strength,
    autoCompletable: false,
    blocks: [{ name: "Tricep pushdown", sets: 2, reps: 10, rpeMax: 6, restSec: 45 }],
  },
  {
    id: "gym_dead_bug",
    kind: "strength",
    title: "Dead Bug",
    flavor: "Low back heavy. Opposite arm and leg.",
    goalTags: [...GYM_GOALS, "mobility"],
    patternTags: ["core"],
    requiredAny: ["none"],
    contraindicationKeys: ["spine"],
    minExperience: 0,
    baseMinutes: 6,
    intensity: "easy",
    statDelta: { vit: 0.16 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Dead bug", sets: 2, reps: 6, rpeMax: 3, notes: "per side" }],
  },
  {
    id: "gym_side_plank",
    kind: "strength",
    title: "Side Plank",
    flavor: "Elbow under shoulder. Knees down is allowed.",
    goalTags: [...GYM_GOALS, "mobility"],
    patternTags: ["core", "isometric"],
    requiredAny: ["none"],
    contraindicationKeys: ["shoulder", "spine"],
    minExperience: 0,
    baseMinutes: 6,
    intensity: "easy",
    statDelta: { vit: 0.14, sta: 0.08 },
    baseXp: BASE_XP.mobility,
    autoCompletable: false,
    blocks: [{ name: "Side plank", sets: 2, seconds: 20, rpeMax: 3, notes: "per side" }],
  },
];
